# Y3K System Startup Script
# Finds available ports, starts payments-api, and builds website with correct API URL

Write-Host "=" * 80 -ForegroundColor Cyan
Write-Host "Y3K SYSTEM STARTUP" -ForegroundColor Cyan
Write-Host "=" * 80 -ForegroundColor Cyan
Write-Host ""

# Function to test if a port is available
function Test-Port {
    param([int]$Port)
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    } catch {
        return $false
    }
}

# Find available port for payments-api
Write-Host "🔍 Finding available port for payments-api..." -ForegroundColor Yellow
$paymentsPorts = @(8080, 8081, 8082, 8083, 8084, 8085)
$availablePort = $null

foreach ($port in $paymentsPorts) {
    if (Test-Port $port) {
        $availablePort = $port
        Write-Host "✅ Port $port is available" -ForegroundColor Green
        break
    } else {
        Write-Host "⏭️  Port $port is in use, trying next..." -ForegroundColor Gray
    }
}

if ($null -eq $availablePort) {
    Write-Host "❌ No available ports found in range 8080-8085" -ForegroundColor Red
    Write-Host "   Please free up one of these ports or kill processes using them" -ForegroundColor Yellow
    exit 1
}

Write-Host ""
Write-Host "🚀 Starting payments-api on port $availablePort..." -ForegroundColor Cyan

# Set environment variables
$env:BIND_ADDRESS = "127.0.0.1:$availablePort"
$env:DATABASE_URL = "sqlite:payments.db"
$env:RUST_LOG = "info"
$env:REQUIRE_STRIPE = "false"

# Check if payments-api binary exists
$paymentsApiPath = ".\target\release\payments-api.exe"
if (-not (Test-Path $paymentsApiPath)) {
    Write-Host "⚠️  payments-api.exe not found, building..." -ForegroundColor Yellow
    cargo build --release --bin payments-api
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Build failed" -ForegroundColor Red
        exit 1
    }
}

# Start payments-api in background
Write-Host "▶️  Launching payments-api..." -ForegroundColor Green
$apiProcess = Start-Process -FilePath $paymentsApiPath -PassThru -NoNewWindow -RedirectStandardOutput "payments-api.log" -RedirectStandardError "payments-api-error.log"

# Wait a moment for it to start
Start-Sleep -Seconds 2

# Check if it's running
if ($apiProcess.HasExited) {
    Write-Host "❌ payments-api failed to start" -ForegroundColor Red
    Write-Host "   Check payments-api-error.log for details" -ForegroundColor Yellow
    Get-Content "payments-api-error.log" -Tail 20
    exit 1
}

Write-Host "✅ payments-api running (PID: $($apiProcess.Id))" -ForegroundColor Green
Write-Host "   URL: http://127.0.0.1:$availablePort" -ForegroundColor Gray
Write-Host "   Logs: payments-api.log" -ForegroundColor Gray
Write-Host ""

# Update y3k-markets-web environment
Write-Host "🔧 Configuring website..." -ForegroundColor Cyan
$webEnvPath = "y3k-markets-web\.env.local"
$envContent = @"
# Auto-generated by start-y3k-system.ps1
NEXT_PUBLIC_API_URL=http://127.0.0.1:$availablePort
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$env:STRIPE_PUBLISHABLE_KEY
"@

Set-Content -Path $webEnvPath -Value $envContent -Force
Write-Host "✅ Website environment configured" -ForegroundColor Green
Write-Host ""

# Check if website should be built
Write-Host "📦 Website options:" -ForegroundColor Cyan
Write-Host "   1. Build for Cloudflare Pages (production)" -ForegroundColor White
Write-Host "   2. Start dev server (local testing)" -ForegroundColor White
Write-Host "   3. Skip website (API only)" -ForegroundColor White
Write-Host ""
$choice = Read-Host "Choose option (1-3)"

if ($choice -eq "1") {
    Write-Host ""
    Write-Host "🏗️  Building for Cloudflare Pages..." -ForegroundColor Cyan
    cd y3k-markets-web
    npm run build
    cd ..
    Write-Host "✅ Build complete: y3k-markets-web/out" -ForegroundColor Green
    Write-Host ""
    Write-Host "📤 Deploy to Cloudflare:" -ForegroundColor Yellow
    Write-Host "   cd y3k-markets-web" -ForegroundColor Gray
    Write-Host "   npx wrangler pages deploy out" -ForegroundColor Gray
} elseif ($choice -eq "2") {
    Write-Host ""
    Write-Host "🌐 Starting dev server..." -ForegroundColor Cyan
    cd y3k-markets-web
    npm run dev
} else {
    Write-Host ""
    Write-Host "⏭️  Skipping website" -ForegroundColor Gray
}

Write-Host ""
Write-Host "=" * 80 -ForegroundColor Cyan
Write-Host "Y3K SYSTEM STATUS" -ForegroundColor Cyan
Write-Host "=" * 80 -ForegroundColor Cyan
Write-Host "✅ payments-api: http://127.0.0.1:$availablePort (PID: $($apiProcess.Id))" -ForegroundColor Green
Write-Host "📁 Logs: payments-api.log, payments-api-error.log" -ForegroundColor Gray
Write-Host ""
Write-Host "To stop payments-api:" -ForegroundColor Yellow
Write-Host "   Stop-Process -Id $($apiProcess.Id)" -ForegroundColor Gray
Write-Host ""
